plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.2'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework:spring-core:6.2.2'
    implementation 'org.springframework:spring-context:6.2.2'
    implementation 'org.telegram:telegrambots:5.3.0'
    compileOnly 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation("org.springframework:spring-test:5.3.30") // Замените на вашу версию

    // JUnit 5 (Jupiter API)
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0") // Замените на вашу версию

    // Mockito Core
    testImplementation("org.mockito:mockito-core:5.5.0") // Замените на вашу версию

    // Mockito JUnit Jupiter
    testImplementation("org.mockito:mockito-junit-jupiter:5.5.0")
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}

tasks.named('test') {
    useJUnitPlatform()
}
